### ISSUE TITLE
search nick as well as text

### ISSUE THREAD

**Issue by bhenderson** [BotBotMe/botbot-web#75] opened 2014-06-27 18:58 UTC
Hi, I was trying to search for some context around an answer I saw in a channel, so I searched for the nick that was mentioned in the response. But because the search term doesn't search by nick, the question wasn't there. I was wondering if you could make it so search terms search nick as well.

eg.

foo: ask some question
... lots of other messages about something else, making it hard to link back to the original question.
bar: foo: answers question

searching for foo only gives the answer, not the question.

I hope that makes sense, thank you for all your work!

**Comment by ipmb** [comment] 2016-03-01 21:06
I think this is a dupe of https://github.com/BotBotMe/botbot-web/issues/21

**Closed by ipmb** 2016-03-01 21:06 UTC
